# Generated by Django 6.0.2 on 2026-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='assigned_area',
            field=models.CharField(blank=True, default='General Area', max_length=150),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
