# Generated by Django 6.0.2 on 2026-02-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('toilets', '0003_toilets_alert_level_toilets_health_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_type',
            field=models.CharField(choices=[('Dirty', 'Dirty'), ('No Water', 'No Water'), ('Broken', 'Broken'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='toilet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilets.toilets'),
        ),
    ]
