# Generated by Django 6.0.2 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_complaint_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="after_image",
            field=models.ImageField(blank=True, null=True, upload_to="complaint_after_images/"),
        ),
    ]
