# Generated by Django 6.0.2 on 2026-02-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='after_video',
            field=models.FileField(blank=True, null=True, upload_to='complaint_after_videos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video_verification_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video_verification_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video_verification_status',
            field=models.CharField(default='Not Checked', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
