# Generated by Django 6.0.2 on 2026-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location_distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='solving_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='solving_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
