# Generated by Django 6.0.2 on 2026-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilets',
            name='cleanliness',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='toilets',
            name='water_level',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='toilets',
            name='status',
            field=models.CharField(default='Good', max_length=50),
        ),
    ]
