# Generated by Django 6.0.2 on 2026-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0002_toilets_cleanliness_toilets_water_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilets',
            name='alert_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='toilets',
            name='health_score',
            field=models.FloatField(default=100.0),
        ),
    ]
