# Generated by Django 6.0.2 on 2026-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0003_toilets_alert_level_toilets_health_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilets',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toilets',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
