# Generated by Django 6.0.2 on 2026-02-18 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toilets", "0004_toilets_latitude_toilets_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toilets",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
