# Generated by Django 6.0.2 on 2026-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toilets", "0006_toiletalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="toilets",
            name="is_disabled_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Enable if this toilet can be used by disabled persons.",
            ),
        ),
    ]
