# Generated by Django 6.0.2 on 2026-02-26 21:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0007_toilets_is_disabled_friendly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toilet_ratings', to=settings.AUTH_USER_MODEL)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='toilets.toilets')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('toilet', 'submitted_by')},
            },
        ),
    ]
