# Generated by Django 6.0.2 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toilets", "0008_toiletrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="toilets",
            name="dustbin_level",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="toilets",
            name="gas_level",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="toilets",
            name="motion_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="toilets",
            name="toilet_type",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Both", "Both")],
                default="Both",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="toiletalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("Low Water", "Low Water"),
                    ("Low Cleanliness", "Low Cleanliness"),
                    ("High Gas", "High Gas"),
                    ("Dustbin Full", "Dustbin Full"),
                ],
                max_length=40,
            ),
        ),
    ]
