# Generated by Django 6.0.2 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toilets", "0009_toilets_sensor_fields_and_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="toiletrating",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User review comment",
                max_length=500,
            ),
            preserve_default=False,
        ),
    ]

