# Generated by Django 6.0.2 on 2026-04-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0010_toiletrating_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_key', models.CharField(choices=[('gas', 'Gas Sensor'), ('water', 'Water Sensor'), ('dustbin', 'Dustbin Sensor'), ('people', 'People Counter Sensor'), ('motion', 'Motion Sensor')], max_length=20, unique=True)),
                ('sensor_name', models.CharField(max_length=80)),
                ('blynk_pin', models.CharField(max_length=10)),
                ('is_working', models.BooleanField(default=False)),
                ('last_value', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_working_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['sensor_name'],
            },
        ),
    ]
