# Generated by Django 6.0.2 on 2026-09-07 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0011_sensorstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Cleaned', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('cleaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_records', to=settings.AUTH_USER_MODEL)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_histories', to='toilets.toilets')),
            ],
            options={
                'verbose_name': 'Cleaning History',
                'verbose_name_plural': 'Cleaning Histories',
                'ordering': ['-cleaned_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=50)),
                ('toilet_name', models.CharField(default='All Toilets / Main Facility', max_length=100)),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('FAILED', 'FAILED'), ('INVALID_DATA', 'INVALID_DATA'), ('NO_RESPONSE', 'NO_RESPONSE')], default='ONLINE', max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('toilet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_failures', to='toilets.toilets')),
            ],
            options={
                'verbose_name': 'Sensor Failure Alert',
                'verbose_name_plural': 'Sensor Failure Alerts',
                'ordering': ['-failed_at'],
            },
        ),
    ]
